### PR TITLE
My first commit

### PR DESCRIPTION
**Pull request by Garima-149**
Display question numbers at each question and correct answer to user when answer selected is wrong @Nitya-Pasrija

### CODE REVIEW

**Comment by Nitya-Pasrija** [comment]
@Garima-149 
Please tag the issue it solves

**Comment by Garima-149** [comment]
Issue no. #20 @Nitya-Pasrija

**Comment by Akanchha112** [comment]
> Issue no. #20 @Nitya-Pasrija



> Issue no. #20 @Nitya-Pasrija

Hello Garima! Congratulations on your first commit🎉! In this commit, we need to change some things like folder structure. Garima, there is already a js file for each thing in Dark And Light Folder, you don't need to create another js file as you have created game.js. You have to go through the code once and see what and where changes need to be made and change only that section. Moreover, I just cloned the changes and it is not working, the correct answer is not showing so make sure you add this functionality in the js file in the Dark and Light folders.

**Comment by Garima-149** [comment]
Screenshot (6)
Screenshot (10)      These 4  files include all the changes I made.
@Akanchha112 Actually,I didn't create a new js file .it already exits in code itself.Do I have to make changes in dark and light file separately?And please do tell ,Do i have to make a new commit after making changes ?

**Comment by Akanchha112** [comment]
> Screenshot (6) Screenshot (10) These 4 files include all the changes I made. @Akanchha112 Actually,I didn't create a new js file .it already exits in code itself.Do I have to make changes in dark and light file separately?And please do tell ,Do i have to make a new commit after making changes ?

Hey @Garima-149! I was mentioning this js file. 
image
ANd yes you have make changes in both light and dark folder for any functionality. And yes you have to commit after making new changes.

**Comment by Garima-149** [comment]
@Akanchha112 @Nitya-Pasrija 
Screenshot (11)
I made commit to this pull request.Please check it.
Screenshot (12)

**Pull request merged**
