### PR TITLE
ADD: Animation on timer

### LINKED ISSUE #37: [UI] Add Animation to timer when less than 5 seconds are remaining.
[UI] Add Animation to the timer when less than 5 seconds are remaining.

DESC: Make timer integer bounce something like as shown below in gif (of 24hrs)

[<iframe src="https://giphy.com/embed/88fKfoAcRCSHPuEbdd" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/crowdfunding-crowdfunder-crowdfunderuk-88fKfoAcRCSHPuEbdd">via GIPHY</a></p>](https://giphy.com/gifs/crowdfunding-crowdfunder-crowdfunderuk-88fKfoAcRCSHPuEbdd)

image

### PR DESCRIPTION
**Pull request by bj-jiwrajka**
Closes #37 

This PR adds animation on timer as requested in #37 , please review @Akanchha112

### CODE REVIEW

**Comment by Akanchha112** [comment]
> Closes #37
> 
> This PR adds animation on timer as requested in #37 , please review @Akanchha112

It does not show animation on the light theme.

**Comment by bj-jiwrajka** [comment]
> > Closes #37
> > This PR adds animation on timer as requested in #37 , please review @Akanchha112
> 
> It does not show animation on the light theme.

please check now, I've fixed it

**Comment by bj-jiwrajka** [comment]
> > Closes #37
> > This PR adds animation on timer as requested in #37 , please review @Akanchha112
> 
> It does not show animation on the light theme.

@Akanchha112 please review

**Comment by bj-jiwrajka** [comment]
@Akanchha112 please review :)

**Pull request merged**
