### PR TITLE
add div of yourScore and "threeButn" for last three buttons

### PR DESCRIPTION
**Pull request by ghost**
before 
Screenshot 2024-01-04 215340

after
Screenshot 2024-01-04 215340

### CODE REVIEW

**Comment by ghost** [comment]
Screenshot 2024-01-04 232601
previous i paste by mistake

**Comment by ghost** [comment]
change css according to the above html file attached

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
The new UI is good, however there are a few conflicts in the files, try a git pull so that your commits are up to date :)

**Comment by ghost** [comment]
di are you able to see my css pr

**Comment by ghost** [comment]
> The new UI is good, however there are a few conflicts in the files, try a git pull so that your commits are up to date :)

di i am unable to make git pull .i had pasted  the problem i am facing during git push 
 remote: Permission to SnowScriptWinterOfCode/QuickQuiz.git denied to sakshiigdtuw.
fatal: unable to access 'https://github.com/SnowScriptWinterOfCode/QuickQuiz.git/': The requested URL returned error: 403
please guide me ....

**Comment by Akanchha112** [comment]
Hello @sakshiigdtw, it seems like you have not merged the commit of the main repo to your forked repo.
image
In your repo, you will be seeing something like this and an option to merge or pull with the main repo. First, save the changes you have made in the UI and then perform that option then again pull the changes in your local folder.

**Pull request closed without merging**
