### PR TITLE
commit for history button

### PR DESCRIPTION
**Pull request by mehaksmansoori**
History button created.
image

### CODE REVIEW

**Review by Nitya-Pasrija — APPROVED** [review]
Looks good :)

**Comment by Akanchha112** [comment]
@mehaksmansoori, the History button is not working. There is no folder like ScoreHistory/index.js
image

**Comment by mehaksmansoori** [comment]
ADDED index.js
image

**Comment by mehaksmansoori** [comment]
#49

**Comment by mehaksmansoori** [comment]
ADDED SPINNER LOADER
image

**Comment by mehaksmansoori** [comment]
ADDED A SPINNER LOADER
image
ISSUE #17

**Comment by mehaksmansoori** [comment]
#17 @Nitya-Pasrija @ayushichoudhary-19 @i-am-SnehaChauhan @Akanchha112 PLZ CHECK

**Comment by mehaksmansoori** [comment]
#17 PLEASE CHECK
@Akanchha112 @Nitya-Pasrija @ayushichoudhary-19 @i-am-SnehaChauhan

**Comment by mehaksmansoori** [comment]
#49 PLEASE CHECK
@Akanchha112 @Nitya-Pasrija @ayushichoudhary-19 @i-am-SnehaChauhan

**Pull request merged**
