### PR TITLE
Remove: Old app

### PR DESCRIPTION
**Pull request by bj-jiwrajka**
There were two apps in the same repository: one was the main one, and the other was within the "updated quiz app" folder. This PR removes the old app and keeps the updated one fixing minor bugs

@i-am-SnehaChauhan @Nitya-Pasrija please review this PR and merge it asap

### CODE REVIEW

**Review by Nitya-Pasrija — COMMENTED** [review]
Perfection! Advancing through the open source world!🎊🎊 :) Please be patient while our maintainers and reviewers check the code.

**Comment by bj-jiwrajka** [comment]
@Akanchha112 please review this PR; since there were 2 different apps.,I deleted the old one. If this PR is merged, it will help others to make contribution in the updated one instead of the old one.

**Comment by Nitya-Pasrija** [comment]
@i-am-SnehaChauhan 
Please look into this PR, and do ask @Akanchaa112 to help you out.

Meanwhile, @bj-jiwrajka there are still conflicts in the index.html and style.css, kindly look into it

**Comment by bj-jiwrajka** [comment]
> @i-am-SnehaChauhan Please look into this PR, and do ask @Akanchaa112 to help you out.
> 
> Meanwhile, @bj-jiwrajka there are still conflicts in the index.html and style.css, kindly look into it

Alright! I've fixed the merge conflict, @i-am-SnehaChauhan can you please check now?

**Comment by bj-jiwrajka** [comment]
@Akanchha112 I've fixed the merge conflict after your recent PR merge, can you please check now?

**Comment by Akanchha112** [comment]
> @Akanchha112 I've fixed the merge conflict after your recent PR merge, can you please check now?

Give me a little bit of time. I will review it and merge it.

**Pull request merged**
