### PR TITLE
FIX: File structure

### LINKED ISSUE #46: Improvement : Fix the messed up file structure
As can be seen , the file structure is really messed up, and there are some redundant as well as repetitive images, I would like to fix that in a minor PR

### PR DESCRIPTION
**Pull request by bj-jiwrajka**
Fixed the file structure, please review and let me know if any further improvements are needed 

Closes #46

### CODE REVIEW

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
Please do not create any edits in the main Readme.md file

**Comment by bj-jiwrajka** [comment]
> Please do not create any edits in the main Readme.md file

okay, I've restored the prev readme, please check now:)

**Comment by bj-jiwrajka** [comment]
> > Please do not create any edits in the main Readme.md file
> 
> okay, I've restored the prev readme, please check now:)

@Akanchha112 please check this one

**Comment by bj-jiwrajka** [comment]
@Nitya-Pasrija @Akanchha112 please checkout this

**Comment by bj-jiwrajka** [comment]
@Akanchha112 please review this

**Pull request closed without merging**
